In [19]:
import pandas as pd
df=pd.read_excel(r"C:\Users\year3\Downloads\Lab Session Data (1).xlsx",sheet_name='Purchase data')
df.head()

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  

[5 rows x 22 columns]

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

# To Load the data
def load_data(file_path, sheet_name):
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    return df

# Function to calculate dimensionality
def dimensions(A):
    dimensionality = numpy.linalg.matrix_rank(A)
    print(f"Dimensionality of the vector space: {dimensionality}")

# Function to count the number of vectors in the DataFrame
def count_vectors(A):
    num_vectors = A.shape[0]
    print(f"Number of vectors in this vector space: {num_vectors}")

# Function to find the rank of Matrix A
def rank_of_matrix(A):
    rank_A = numpy.linalg.matrix_rank(A)
    print(f"Rank of Matrix A: {rank_A}")

# Function to compute pseudo-inverse and find costs
def compute_costs(A, C):
    A_pseudo_inv = np.linalg.pinv(A)
    X = np.dot(A_pseudo_inv, C)
    return X


# Function to mark customers as RICH or POOR and build a classifier
def classify_customers(df):
    # Mark customers
    df['Class'] = np.where(df['Payment (Rs)'] > 200, 'RICH', 'POOR')
   
    # Prepare features and labels
    X = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
    y = df['Class'].values
   
    # Standardize features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
   
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)
   
    # Train a logistic regression model
    model = LogisticRegression()
    model.fit(X_train, y_train)
   
    # Predict on the test set
    y_pred = model.predict(X_test)
   
    # Print classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

# Main function to execute the tasks
def main():
    # Load the data
    file_path = r"C:\Users\year3\Downloads\Lab Session Data (1).xlsx"
    sheet_name = 'Purchase data'
    df = load_data(file_path, sheet_name)

    # Selection of specific columns
    columns_to_print = df[['Customer', 'Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)', 'Payment (Rs)']]
    print("Selected columns:")
    print(columns_to_print)
   
    # Create matrices A and C
    A = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
    C = df[['Payment (Rs)']].values
   
    # Print matrices
    print("\nMatrix A:")
    print(A)
    print("\nMatrix C:")
    print(C)
   
    # Perform calculations
    dimensions(A)
    count_vectors(A)
    rank_of_matrix(A)
    X = compute_costs(A, C)
    print("\nCost of each product available for sale:")
    print(X)
   
    # Classify customers
    classify_customers(df)

# Execute the main function
if __name__ == "__main__":
    main()

Selected columns:
  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

Matrix A:
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

Matrix C:
[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
